# odi-tools configuration file
basic:
  object: GCPair-F1                           # the name of your object
  filters: [odi_g, odi_r]               # correct filter strings required
  instrument: 5odi                      # podi | 5odi | mosaic; script will verify using image header info

processing: # optional steps performed in odi_process.py
  remove_tpv: yes
  trim_image: yes
  wcs_correction: yes
  trim_section: [2508,15798,2216,15506] #[x1:x2,y1:y2]
  airmasses: [1.0,1.0] #same order as filters
  new_extension: .trim-nopv.fits

# list the images you want to process
# be sure to associate the filename with the correct dither pointing!
# OBSID and image header are NOT always an accurate reflection of the absolute dither position
# so you must use your notes / observing log to define them here
# sections must be named according to the filter names

odi_g:
  1: GCPair-F1_odi_g.fits

odi_r:
  1: GCPair-F1_odi_r.fits
